# Generated by Django 4.2.5 on 2023-09-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_id',
        ),
    ]
